-- NewsPeaper Supabase Schema

-- 1. Create categories table
CREATE TABLE categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create posts table
CREATE TABLE posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  content TEXT NOT NULL,
  featured_image TEXT,
  category_id BIGINT REFERENCES categories(id),
  author_id UUID REFERENCES auth.users(id),
  status TEXT DEFAULT 'published',
  views BIGINT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Enable Row Level Security (RLS)
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE posts ENABLE ROW LEVEL SECURITY;

-- 4. Create Policies

-- Categories: Everyone can read
CREATE POLICY "Allow public read access for categories" ON categories
  FOR SELECT USING (true);

-- Categories: Only authenticated users can insert/update/delete
CREATE POLICY "Allow authenticated users to manage categories" ON categories
  FOR ALL TO authenticated USING (true);

-- Posts: Everyone can read published posts
CREATE POLICY "Allow public read access for published posts" ON posts
  FOR SELECT USING (status = 'published');

-- Posts: Only authenticated users can manage posts
CREATE POLICY "Allow authenticated users to manage posts" ON posts
  FOR ALL TO authenticated USING (true);

-- 5. Create Storage Bucket
-- Note: You need to create a bucket named 'news-images' in the Supabase Dashboard
-- and set its privacy to 'Public'.

-- 6. Insert Initial Categories
INSERT INTO categories (name, slug) VALUES 
('Politics', 'politics'),
('Technology', 'technology'),
('Sports', 'sports'),
('Entertainment', 'entertainment'),
('Business', 'business');
